theme: jekyll-theme-cayman
title: "Ishaan Mahajan"
description: I am undergraduate student at the University of Wisconsin-Madison studying Computer Science and Data Science. I am deeply interested in the applications of autonomous technology using machine learning, and software development and tackling complex real-world using the same.  
