
layout: default
remote_theme: pages-themes/time-machine@v0.2.0
title: ISHAAN MAHAJAN
description: ! (https://github.com/ishaanamahajan/ishaanamahajan.github.io/blob/main/assets/css/Ishaan_Picture.jpeg) I am an undergraduate student at the University of Wisconsin-Madison studying Computer Science and Data Science, along with a certificate in Economic Analytics. I am deeply interested in the applications of autonomous technology using machine learning, and software development and tackling complex real-world using the same.  
