

remote_theme: pages-themes/minimal@v0.2.0
title: ISHAAN MAHAJAN
description: A personal website

![Image](https://raw.githubusercontent.com/ishaanamahajan/ishaanamahajan.github.io/main/PersonalImage.png)


